spring:
  application:
    name: CommodityPriceMangementSystem
  

  datasource:
    url: jdbc:h2:mem:commoditydb
    username: surya
    password: surya
  h2:
    console:
      enabled: true  
      
      
      
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    